on:
  workflow_call: {}

jobs:
  release:
    name: washboard-ui

    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/typescript/apps/washboard-ui/v')

    steps:
      - name: Download Asset
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: washboard

      - name: Create Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          draft: false
          prerelease: false
          makeLatest: false
          artifacts: washboard.tar.gz